In [115]:
import pandas as pd
import os
os.getcwd()

'f:\\data-visualization-lab\\asessing_data'

In [116]:
df = pd.read_excel('Job survey.xlsx')
df.head(15)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Browser,OS,City,Country,Referrer,Time Spent,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,NaN,NaN,NaN,NaN,NaN,0:00:44,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,NaN,NaN,NaN,NaN,NaN,0:01:30,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,NaN,NaN,NaN,NaN,NaN,0:02:18,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,NaN,NaN,NaN,NaN,NaN,0:02:10,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:01:51,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American
5,62a33cb6cf25554317300177,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:02:34,...,3.0,3.0,2.0,Difficult,Good Work/Life Balance,Male,33,Other (Please Specify):Republic democratic of ...,NaN,Black or African American
6,62a33cb72e54c9003e531c65,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:01:15,...,6.0,6.0,5.0,Difficult,Better Salary,Male,24,Other (Please Specify),NaN,Black or African American
7,62a33cd30f8c8599d5af0f8f,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:01:25,...,5.0,5.0,9.0,Neither easy nor difficult,Remote Work,Male,35,United States,NaN,Asian or Asian American
8,62a33cd3cf255543173001d9,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:02:10,...,4.0,5.0,5.0,Neither easy nor difficult,Better Salary,Male,35,United States,NaN,Asian or Asian American
9,62a33cd8bc6861bf3176c05f,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:01:27,...,3.0,0.0,4.0,Very Difficult,Better Salary,Male,28,United States,NaN,Hispanic or Latino
10,62a33ce918134ddc75ce8c30,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:01:29,...,8.0,8.0,10.0,Neither easy nor difficult,Remote Work,Male,37,Canada,NaN,White or Caucasian
11,62a33cf30a77c1a77f65baa2,anonymous,6/10/2022,8:45,NaN,NaN,NaN,NaN,NaN,0:02:31,...,10.0,7.0,8.0,Neither easy nor difficult,Better Salary,Male,32,Other (Please Specify):Serbia,NaN,White or Caucasian
12,62a33d15f408bae018ed370d,anonymous,6/10/2022,8:46,NaN,NaN,NaN,NaN,NaN,0:03:20,...,9.0,5.0,10.0,Neither easy nor difficult,Better Salary,Male,34,Other (Please Specify):Argentina,NaN,Other (Please Specify):Latino with Italian roots
13,62a33d1ebae91e4b8b82e707,anonymous,6/10/2022,8:46,NaN,NaN,NaN,NaN,NaN,0:00:55,...,6.0,7.0,8.0,Easy,Good Work/Life Balance,Male,30,United Kingdom,NaN,White or Caucasian
14,62a33d4624a26260273824c4,anonymous,6/10/2022,8:47,NaN,NaN,NaN,NaN,NaN,0:01:24,...,5.0,4.0,5.0,Neither easy nor difficult,Good Culture,Male,31,United States,NaN,White or Caucasian

In [118]:
df.shape

(630, 28)

In [119]:
df.describe()

,Browser,OS,City,Country,Referrer,Q6 - How Happy are you in your Current Position with the following? (Salary),Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance),Q6 - How Happy are you in your Current Position with the following? (Coworkers),Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q10 - Current Age
count,0.0,0.0,0.0,0.0,0.0,623.000000,620.000000,619.000000,618.000000,617.000000,625.000000,630.000000
mean,NaN,NaN,NaN,NaN,NaN,4.269663,5.741935,5.861066,5.326861,4.756888,5.608000,30.152381
std,NaN,NaN,NaN,NaN,NaN,2.772945,2.761584,2.703244,2.738161,2.820822,3.006659,9.913888
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
25%,NaN,NaN,NaN,NaN,NaN,2.000000,4.000000,4.000000,4.000000,3.000000,3.000000,25.000000
50%,NaN,NaN,NaN,NaN,NaN,4.000000,6.000000,6.000000,5.000000,5.000000,6.000000,28.000000
75%,NaN,NaN,NaN,NaN,NaN,7.000000,8.000000,8.000000,7.000000,7.000000,8.000000,33.000000
max,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,200.000000

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 28 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Unique ID                                                                                     630 non-null    str
 1   Email                                                                                         630 non-null    str
 2   Date Taken (America/New_York)                                                                 630 non-null    str
 3   Time Taken (America/New_York)                                                                 630 non-null    str
 4   Browser                                                                                       0 non-null      float64
 5   OS                                                                                            0 non-null      float64
 6   City                                                                                          0 non-null      float64
 7   Country                                                                                       0 non-null      float64
 8   Referrer                                                                                      0 non-null      float64
 9   Time Spent                                                                                    630 non-null    str
 10  Q1 - Which Title Best Fits your Current Role?                                                 630 non-null    str
 11  Q2 - Did you switch careers into Data?                                                        630 non-null    str
 12  Q3 - Current Yearly Salary (in USD)                                                           630 non-null    str
 13  Q4 - What Industry do you work in?                                                            630 non-null    str
 14  Q5 - Favorite Programming Language                                                            630 non-null    str
 15  Q6 - How Happy are you in your Current Position with the following? (Salary)                  623 non-null    float64
 16  Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)       620 non-null    float64
 17  Q6 - How Happy are you in your Current Position with the following? (Coworkers)               619 non-null    float64
 18  Q6 - How Happy are you in your Current Position with the following? (Management)              618 non-null    float64
 19  Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)         617 non-null    float64
 20  Q6 - How Happy are you in your Current Position with the following? (Learning New Things)     625 non-null    float64
 21  Q7 - How difficult was it for you to break into Data?                                         630 non-null    str
 22  Q8 - If you were to look for a new job today, what would be the most important thing to you?  630 non-null    str
 23  Q9 - Male/Female?                                                                             630 non-null    str
 24  Q10 - Current Age                                                                             630 non-null    int64
 25  Q11 - Which Country do you live in?                                                           630 non-null    str
 26  Q12 - Highest Level of Education                                                              578 non-null    str
 27  Q13 - Ethnicity                                                                               630 non-null    str
dtypes: float64(11), int64(1), str(16)
memory usage: 137.9 KB

# Completeness

- Các cột Browser, OS, City, Country, Referrer, bị null 100%, vậy ta sẽ drop các cột này
- Với các giá trị null của các cột How happy are you (Salary, Salary, Coworkers, Management, Upward Mobility, Learning New Things), ta sẽ điền giá trị mean, vì các cột này không có outliers (max=10, min=0 và std~=2.7)
- Với các giá trị null của cột Q12 - Highest Level of Education thì ta sẽ điền giá trị mode, vì đây là cột categorical

In [122]:
cols = ['Browser', 'OS', 'City', 'Country', 'Referrer']

for col in cols:
    df.drop(col, axis=1, inplace=True)

In [123]:
happy_cols = [
    'Q6 - How Happy are you in your Current Position with the following? (Salary)',
    'Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)',
    'Q6 - How Happy are you in your Current Position with the following? (Coworkers)',
    'Q6 - How Happy are you in your Current Position with the following? (Management)',
    'Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)',
    'Q6 - How Happy are you in your Current Position with the following? (Learning New Things)',
]

for happy_col in happy_cols:
    df[happy_col] = df[happy_col].fillna(df[happy_col].mean())

In [124]:
df['Q12 - Highest Level of Education'] = df['Q12 - Highest Level of Education'].fillna(df['Q12 - Highest Level of Education'].mode()[0])

DataFrame sau khi xử lý giá trị null

In [125]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 23 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Unique ID                                                                                     630 non-null    str
 1   Email                                                                                         630 non-null    str
 2   Date Taken (America/New_York)                                                                 630 non-null    str
 3   Time Taken (America/New_York)                                                                 630 non-null    str
 4   Time Spent                                                                                    630 non-null    str
 5   Q1 - Which Title Best Fits your Current Role?                                                 630 non-null    str
 6   Q2 - Did you switch careers into Data?                                                        630 non-null    str
 7   Q3 - Current Yearly Salary (in USD)                                                           630 non-null    str
 8   Q4 - What Industry do you work in?                                                            630 non-null    str
 9   Q5 - Favorite Programming Language                                                            630 non-null    str
 10  Q6 - How Happy are you in your Current Position with the following? (Salary)                  630 non-null    float64
 11  Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)       630 non-null    float64
 12  Q6 - How Happy are you in your Current Position with the following? (Coworkers)               630 non-null    float64
 13  Q6 - How Happy are you in your Current Position with the following? (Management)              630 non-null    float64
 14  Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)         630 non-null    float64
 15  Q6 - How Happy are you in your Current Position with the following? (Learning New Things)     630 non-null    float64
 16  Q7 - How difficult was it for you to break into Data?                                         630 non-null    str
 17  Q8 - If you were to look for a new job today, what would be the most important thing to you?  630 non-null    str
 18  Q9 - Male/Female?                                                                             630 non-null    str
 19  Q10 - Current Age                                                                             630 non-null    int64
 20  Q11 - Which Country do you live in?                                                           630 non-null    str
 21  Q12 - Highest Level of Education                                                              630 non-null    str
 22  Q13 - Ethnicity                                                                               630 non-null    str
dtypes: float64(6), int64(1), str(16)
memory usage: 113.3 KB

# Validity & Accuracy
- Trong các cột có giá trị số thì cột Current Age xuất hiện 2 dòng có giá trị là 200 và 92 tuổi, ta sẽ thay thế 2 giá trị này bằng cách điền giá trị mean mới. Giá trị mean mới sẽ được tính trên toàn bộ dataset sau khi đã loại bỏ 2 giá trị này, tránh bị nó kéo lệch. Các dòng nào có tuổi dưới 70 ta vẫn giữ nguyên.

- Các cột có giá trị số khác đều đảm bảo được Validity và Accuracy, vì chúng là các cột đánh giá, đều nằm trong đoạn [0;10]

In [141]:
new_mean = round(df[df['Q10 - Current Age']<70]['Q10 - Current Age'].mean())

df.loc[df['Q10 - Current Age'] > 70, 'Q10 - Current Age'] = new_mean

# Consistency

- Cột Date Taken (America/New_York) đã được tính ở format m/dd/yyyy theo định dạng của Mỹ, không cần xử lý cột này
- Cột Q3 - Current Yearly Salary (in USD) được format theo dạng khoảng (VD: 41k-65k) và đã có đơn vị USD đồng nhất, nên không xử lý cột này
- Cột Q2 - Did you switch careers into Data? chỉ có 2 giá trị Yes/No, không có 1/0, nên sẽ không cần xử lý cột này

Vậy Consistency ok

In [121]:
df.duplicated().sum()

np.int64(0)

# Uniqueness

- Không có dòng trùng, uniqueness ok

DataFrame sau khi được đánh giá và xử lý qua 5 bước

In [146]:
df.head(15)

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Time Spent,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,Bachelors,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,0:01:30,Data Analyst,No,41k-65k,Finance,R,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,Bachelors,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,Bachelors,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,Bachelors,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,Bachelors,Black or African American
5,62a33cb6cf25554317300177,anonymous,6/10/2022,8:44,0:02:34,Data Analyst,Yes,0-40k,Other (Please Specify):Coworking space,Python,...,3.0,3.0,2.0,Difficult,Good Work/Life Balance,Male,33,Other (Please Specify):Republic democratic of ...,Bachelors,Black or African American
6,62a33cb72e54c9003e531c65,anonymous,6/10/2022,8:44,0:01:15,Data Scientist,Yes,0-40k,Finance,Python,...,6.0,6.0,5.0,Difficult,Better Salary,Male,24,Other (Please Specify),Bachelors,Black or African American
7,62a33cd30f8c8599d5af0f8f,anonymous,6/10/2022,8:45,0:01:25,Data Engineer,Yes,125k-150k,Other (Please Specify):Retail,Other:SQL,...,5.0,5.0,9.0,Neither easy nor difficult,Remote Work,Male,35,United States,Bachelors,Asian or Asian American
8,62a33cd3cf255543173001d9,anonymous,6/10/2022,8:45,0:02:10,Data Analyst,Yes,86k-105k,Healthcare,R,...,4.0,5.0,5.0,Neither easy nor difficult,Better Salary,Male,35,United States,Bachelors,Asian or Asian American
9,62a33cd8bc6861bf3176c05f,anonymous,6/10/2022,8:45,0:01:27,Data Analyst,Yes,41k-65k,Telecommunication,Python,...,3.0,0.0,4.0,Very Difficult,Better Salary,Male,28,United States,Bachelors,Hispanic or Latino
10,62a33ce918134ddc75ce8c30,anonymous,6/10/2022,8:45,0:01:29,Data Analyst,Yes,66k-85k,Other (Please Specify):Logistics,Python,...,8.0,8.0,10.0,Neither easy nor difficult,Remote Work,Male,37,Canada,Bachelors,White or Caucasian
11,62a33cf30a77c1a77f65baa2,anonymous,6/10/2022,8:45,0:02:31,Data Analyst,Yes,0-40k,Other (Please Specify):Igaming,Python,...,10.0,7.0,8.0,Neither easy nor difficult,Better Salary,Male,32,Other (Please Specify):Serbia,Bachelors,White or Caucasian
12,62a33d15f408bae018ed370d,anonymous,6/10/2022,8:46,0:03:20,Data Analyst,Yes,0-40k,Tech,R,...,9.0,5.0,10.0,Neither easy nor difficult,Better Salary,Male,34,Other (Please Specify):Argentina,Bachelors,Other (Please Specify):Latino with Italian roots
13,62a33d1ebae91e4b8b82e707,anonymous,6/10/2022,8:46,0:00:55,Data Scientist,Yes,0-40k,Education,Python,...,6.0,7.0,8.0,Easy,Good Work/Life Balance,Male,30,United Kingdom,Bachelors,White or Caucasian
14,62a33d4624a26260273824c4,anonymous,6/10/2022,8:47,0:01:24,Data Analyst,No,41k-65k,Construction,R,...,5.0,4.0,5.0,Neither easy nor difficult,Good Culture,Male,31,United States,Bachelors,White or Caucasian